[package]
name = "final_project_rust"
version = "0.1.0"
authors = ["Robert Bacon <rb40345@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.5"
usb = "0.2.2"